// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession()
    let session = data.session

    // getSession() can hand back an already-expired access token (the automatic
    // refresh may not have fired yet), which makes the server reject the RPC
    // with "Unauthorized: Invalid token". Refresh proactively when needed.
    const expiresAt = session?.expires_at ? session.expires_at * 1000 : 0
    if (session && expiresAt - Date.now() < 60_000) {
      const refreshed = await supabase.auth.refreshSession()
      session = refreshed.data.session ?? session
    }

    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)

