// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    // Le runtime serveur ne charge pas forcément .env : repli sur les VITE_*
    // (remplacées au build) puis sur les valeurs publiques du projet AcreMap,
    // comme le client navigateur. SUPABASE_ANON_KEY est l'ancien nom de la clé publicable.
    const SUPABASE_URL =
      process.env.SUPABASE_URL ??
      process.env.VITE_SUPABASE_URL ??
      (import.meta.env?.VITE_SUPABASE_URL as string | undefined) ??
      "https://ckkjqpsoavrikgiuuktf.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ??
      process.env.SUPABASE_ANON_KEY ??
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
      (import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNra2pxcHNvYXZyaWtnaXV1a3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NDY1MDYsImV4cCI6MjEwMjEyMjUwNn0.XJREMPDEOyswhr7bLGE0TwKaRQyCWmcAiyPBitAPOOU";
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Validate against Supabase Auth directly: works with both legacy HS256 and
    // asymmetric (JWKS) signing keys, unlike local claim verification.
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      throw new Error('Unauthorized: Invalid token');
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: { sub: data.user.id, email: data.user.email },
      },
    });
  },
);
